export const comentariosInicialState = {
	comentarioFugaAceite: '',
	comentarioFugaCombustible: '',
	comentarioFugaAceiteMotor: '',
	comentarioDireccionalesDelanteras: '',
	comentarioDireccionalesTraseras: '',
	comentarioLucesTablero: '',
	comentarioLuzFreno: '',
	comentarioLlantaDelantera: '',
	comentarioLlantaTrasera: '',
	comentarioDeformacionesLlanta: '',
	comentarioEncendido: '',
	comentarioTensionCadena: '',
	comentarioFrenoDelantero: '',
	comentarioFrenoTrasero: '',
	comentarioAmortiguadores: '',
	comentarioDireccion: '',
	comentarioSilla: '',
	comentarioEspejos: '',
	comentarioVelocimetro: '',
	comentaroioClaxon: '',
	comentarioPalancas: ''
}