export const documentosInicialState = {
	tarjetaCirculacion: null,
	factura: null,
	seguro: null,
	garantia: null,
	frente: null,
	trasera: null,
	ladoDerecho: null, 
	ladoIzquierdo: null,
	nombreTarjetaCirculacion: '',
	nombreFactura: '',
	nombreSeguro: '',
	nombreGarantia: '',
	previewFrente: null,
	previewTrasera: null,
	previewLadoIzquierdo: null,
	previewLadoDerecho: null,
}