export const editarInformacionGeneralInitialState = {
	editKilometraje: '',
	editSelectedPlace: 0,
	editImage: null,
	editImagePreview: null,
	editModelo: '',
	editPlaca: '',
	editVehiculo: '',
	editMarca: '',
	editSerie:'',
	editColor:'',
	editColorLlavero:'',
	editTipoMotor:'',
	editImagenDelantera:null,
	editImagenTrasera:null,
	editImagenIzquierda:null,
	editImagenDerecha:null,
	editImagenDelanteraPreview:null,
	editImagenTraseraPreview:null,
	editImagenIzquierdaPreview:null,
	editImagenDerechaPreview:null,
	editFactura:'',
	editCirculacion:'',
	editSeguro:'',
	editGarantia:'',
}

