export const estadoInicialState = {
	combustible: '',
	bateria: '',
	neumaticos: '',
	fugaAceite: false,
	fugaCombustible: false,
	fugaAceiteMotor: false,
	direccionalesDelanteras: false,
	direccionalesTraseras: false,
	lucesTablero: false,
	luzFreno: false,
	llantaDelantera: false,
	llantaTrasera: false,
	deformacionesLlanta: false,
	encendido: false,
	tensionCadena: false,
	frenoDelantero: false,
	frenoTrasero: false,
	amortiguadores: false,
	direccion: false,
	silla: false,
	espejos: false,
	velocimetro: false,
	claxon: false,
	palancas: false,
	observaciones: '',
}