export const imagenesEstadoStates = {
	imagenesFugaAceite: null,
	imagenesFugaCombustible: null,
	imagenesFugaAceiteMotor: null,
	imagenesDireccionalesDelanteras: null,
	imagenesDireccionalesTraseras: null,
	imagenesLucesTablero: null,
	imagenesLuzFreno: null,
	imagenesLlantaDelantera: null,
	imagenesLlantaTrasera: null,
	imagenesDeformacionesLlanta: null,
	imagenesEncendido: null,
	imagenesTensionCadena: null,
	imagenesFrenoDelantero: null,
	imagenesFrenoTrasero: null,
	imagenesAmortiguadores: null,
	imagenesSilla: null,
	imagenesEspejos: null,
	imagenesVelocimetro: null,
	imagenesClaxon: null,
	imagenesPalancas: null,
}