export const esES = {
    toolbarColumns: "Columnas",
    toolbarFilters: "Filtros",
    toolbarDensity: "Densidad",
    toolbarExport: "Exportar",
    columnsPanelTextFieldLabel: "Buscar columna",
    columnsPanelTextFieldPlaceholder: "Buscar columna",
    columnsPanelDragIconLabel: "Arrastrar",
    filterPanelTitle: "Filtros",
    filterPanelSearchPlaceholder: "Buscar",
    filterOperatorContains: "Contiene",
    filterOperatorEquals: "Es igual a",
    filterOperatorStartsWith: "Empieza con",
    filterOperatorEndsWith: "Termina con",
    filterOperatorIs: "Es",
    filterOperatorNot: "No es",
    filterOperatorIsEmpty: "Está vacío",
    filterOperatorIsNotEmpty: "No está vacío",
    filterOperatorBefore: "Antes",
    filterOperatorAfter: "Después",
    filterOperatorOnOrBefore: "El o antes",
    filterOperatorOnOrAfter: "El o después",
    filterOperatorIsNull: "Es nulo",
    filterOperatorIsNotNull: "No es nulo",
    columnMenuUnsort: "Desordenar",
    columnMenuSortAsc: "Ordenar ascendente",
    columnMenuSortDesc: "Ordenar descendente",
    columnMenuFilter: "Filtrar",
    columnMenuHideColumn: "Ocultar columna",
    columnMenuShowColumns: "Mostrar columnas",
    columnMenuPinLeft: "Fijar a la izquierda",
    columnMenuPinRight: "Fijar a la derecha",
    columnMenuReset: "Restablecer",
    columnMenuSort: "Ordenar",
    columnMenuFilterMenu: "Menú de filtros",
    columnMenuToggleFilter: "Alternar filtro",
    columnMenuHide: "Ocultar",
    columnMenuShow: "Mostrar",
    columnMenuGroup: "Agrupar",
    columnMenuUnGroup: "Desagrupar",
    columnMenuExpandAll: "Expandir todo",
    columnMenuCollapseAll: "Colapsar todo",
    columnMenuRename: "Renombrar",
  };
  